services:
  - type: web
    name: epf-plotter
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn basic:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
